Adding Grade F Prime Beef
ADDVulcan/Writeups pull request #7
Opened 2021-06-27 20:19 UTC by 5hu5ky

Initial commit

2021-06-27 20:32 UTC, mossmann requested changes
Looks great with one change! Thanks for being the first to submit a writeup!

2021-06-27 20:32 UTC, mossmann commented on Hack-A-Sat 2021/Rapid Unplanned Disassembly/Grade F Prime Beef/grade_f_write_up.md
> +FLAG=flag{sierra457871juliet2:XXXXXXXXXXXXXXXXXXXXXXXX_XXXXXXXXXXXXXXXX_XXXXXXXXXXXXXXXXXXXXXXXX_XXXXXXXXXXXXXXXX}
The flag is redacted here but not in the `grep.log` above. Can you please unredact this one since we are only redacting tickets?

2021-06-28 00:05 UTC, 5hu5ky commented
Good catch! Fixed it...

2021-06-28 00:23 UTC, merged

2021-06-28 00:46 UTC, mossmann commented
I merged this to the wrong branch but then cherry-picked it into main.